### ISSUE TITLE
Failed to import data with error `TIMEOUT_EXCEEDED`

### ISSUE THREAD

**Issue by shirley-gu-timeplus** [timeplus-io/sling-cli#12]
## Issue Description

- Description of the issue: 

- Sling version (`sling --version`): 
dev (1.0.3)
- Operating System (`linux`, `mac`, `windows`): 
linux
- Replication Configuration: 
~/.sling/env.yaml
```
connections:
  daily_timeplus:
    url: 'proton://default@172.31.29.101:30863/default'

  historical_timeplus:
    type: proton
    host: 172.31.29.101
    user: default
    password: ""
    port: 30863
    database: default
```
daily_test.yaml
```yaml
source: DAILY_TIMEPLUS
target: HISTORICAL_TIMEPLUS

defaults:
  mode: incremental

streams:
  my_src:
    update_key: _tp_time
    object: my_tar
```

- Log Output (please run command with `-d`): 

```
[root@node0 sling]# ./sling-timeplus run -r daily_test.yaml
WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
9:10PM INF Sling Replication [1 streams] | DAILY_TIMEPLUS -> HISTORICAL_TIMEPLUS

9:10PM INF [1 / 1] running stream my_src
9:10PM INF connecting to source database (proton)
9:10PM INF connecting to target database (proton)
9:10PM INF getting checkpoint value
9:10PM INF reading from source database
9:10PM INF writing to target database [mode: incremental]
9:10PM INF streaming data
9:10PM INF Retrying after error: ~ could not send batch data
code: 159, message: Failed to ingest data, error='TIMEOUT_EXCEEDED'
9:10PM INF execution failed
Loaded 0 records while sample data has 3 records. Exiting.

9:10PM INF Sling Replication Completed in 11s | DAILY_TIMEPLUS -> HISTORICAL_TIMEPLUS | 0 Successes | 1 Failures

fatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- my_src ---------------------------
~ Could not WriteToDb
Loaded 0 records while sample data has 3 records. Exiting.

```
