### ISSUE TITLE
column name issue when import data to target table

### ISSUE THREAD

**Issue by shirley-gu-timeplus** [timeplus-io/sling-cli#34]
## Issue Description

- Description of the issue: 
When import data into target table, unexpected column name found which cause import failure
issue1: No such column a1 in stream default.gj_rtdc_oms_order_statistics
issue2: provided field 'securityid1' not found in table `default`.`gj_i_futurePositionAmount_fix3`

- Sling version (`sling --version`): 
1.2.20-rc10-timeplus
1.2.20-rc8-timeplus

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 

```yaml
source: DAILY_TIMEPLUS
target: HISTORICAL_TIMEPLUS

defaults:
  mode: incremental

streams:
  rtdc_exchange_order:
    update_key: _tp_time
    object: gj_rtdc_exchange_order
  rtdc_execution:
    update_key: _tp_time
    object: gj_rtdc_execution
  rtdc_position:
    update_key: _tp_time
    object: gj_rtdc_position
  rtdc_fund:
    update_key: _tp_time
    object: gj_rtdc_fund
  t_metrics:
    update_key: _tp_time
    object: gj_metrics
  stock_xshg_ext:
    update_key: _tp_time
    object: gj_stock_xshg_ext
  rtdc_o32_fundflow:
    update_key: _tp_time
    object: gj_rtdc_o32_fundflow
  rtdc_oms_order_statistics:
    update_key: _tp_time
    object: gj_rtdc_oms_order_statistics
  stock:
    update_key: _tp_time
    object: gj_stock
  future_ccfx_ext:
    update_key: _tp_time
    object: gj_future_ccfx_ext
  i_t0_kpi:
    update_key: _tp_time
    object: gj_i_t0_kpi
  i_positionHoldingAmount_fix4:
    update_key: _tp_time
    object: gj_i_positionHoldingAmount_fix4
  i_positionHoldingAmount_fix3:
    update_key: _tp_time
    object: gj_i_positionHoldingAmount_fix3
  i_positionHoldingAmount_fix2:
    update_key: _tp_time
    object: gj_i_positionHoldingAmount_fix2
  i_positionHoldingAmount_fix1:
    update_key: _tp_time
    object: gj_i_positionHoldingAmount_fix1
  i_order_delay_10d_1m:
    update_key: _tp_time
    object: gj_i_order_delay_10d_1m
  i_netSportPurchase:
    update_key: _tp_time
    object: gj_i_netSportPurchase
  i_futurePositionAmount_fix4:
    update_key: _tp_time
    object: gj_i_futurePositionAmount_fix4
  i_futurePositionAmount_fix3:
    update_key: _tp_time
    object: gj_i_futurePositionAmount_fix3
  i_futurePositionAmount_fix2:
    update_key: _tp_time
    object: gj_i_futurePositionAmount_fix2
  i_futurePositionAmount_fix1:
    update_key: _tp_time
    object: gj_i_futurePositionAmount_fix1
  future_ccfx:
    update_key: _tp_time
    object: gj_future_ccfx
```

- Log Output (please run command with `-d`): 

[1023_sling_rc8_i_futurePositionAmount_fix3.log](https://github.com/user-attachments/files/17487731/1023_sling_rc8_i_futurePositionAmount_fix3.log)
[1023_sling_rc8_rtdc_oms_order_statistics.log](https://github.com/user-attachments/files/17487736/1023_sling_rc8_rtdc_oms_order_statistics.log)
