### ISSUE TITLE
failed to import data into database when stream contains `a.b` field

### ISSUE THREAD

**Issue by shirley-gu-timeplus** [timeplus-io/sling-cli#36]
## Issue Description

- Description of the issue: 
failed to import data into database when stream contains `a.b` field

- Sling version (`sling --version`): 
1.2.20-rc11-timeplus
1.2.20-rc13-timeplus

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 

```yaml
source: DAILY_TIMEPLUS
target: HISTORICAL_TIMEPLUS
streams:
  i_positionHoldingAmount_fix3:
    update_key: _tp_time
    object: gj_i_positionHoldingAmount_fix3
```

- Log Output (please run command with `-d`): 

```
~ could not bulk import
--- database.go:1590 GetColumns ---
~ could not get matching list of columns from table
--- database.go:1506 GetTableColumns ---
provided field 'd__tp_time' not found in table `default`.`gj_i_positionHoldingAmount_fix3
```
[1024_sling_rc11_i_positionHoldingAmount_fix3.log](https://github.com/user-attachments/files/17506705/1024_sling_rc11_i_positionHoldingAmount_fix3.log)
